name: automated_testing_framework_models
description: Core models for the automated testing framework to provide pure dart support for server side integrations.
version: 2.0.3+1
homepage: https://github.com/peiffer-innovations/automated_testing_framework_models

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  convert: ^3.0.0
  json_class: ^2.0.0+1
  logging: ^1.0.1
  meta: ^1.4.0
  pointycastle: ^3.0.1
  uuid: ^3.0.4

dev_dependencies:
  test: any
