name: automated_testing_framework_models
description: Core models for the automated testing framework to provide pure dart support for server side integrations.
version: 1.0.0
homepage: https://github.com/peiffer-innovations/automated_testing_framework_models

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  json_class: ^1.0.6+1
  meta: ^1.1.8
  pointycastle: ^2.0.0
  uuid: ^2.2.2

dev_dependencies:
  test: any
  test_coverage: any
