name: 'automated_testing_framework_models'
description: 'Core models for the automated testing framework to provide pure dart support for server side integrations.'
version: '2.0.9+5'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_models'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  convert: '^3.0.2'
  json_class: '^2.1.2+8'
  logging: '^1.0.2'
  meta: '^1.7.0'
  pointycastle: '^3.6.0'
  uuid: '^3.0.6'

dev_dependencies: 
  test: '^1.21.4'

ignore_updates: 
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'term_glyph'
  - 'vector_math'
