name: 'automated_testing_framework_models'
description: 'Core models for the automated testing framework to provide pure dart support for server side integrations.'
version: '2.0.9+16'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_models'

environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  convert: '^3.1.1'
  json_class: '^2.1.4+1'
  logging: '^1.1.0'
  meta: '^1.7.0'
  pointycastle: '^3.6.2'
  uuid: '^3.0.7'

dev_dependencies: 
  test: '^1.22.2'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
